version: '3'
services:
  app:
    image: node:18-alpine
    container_name: customer_portal
    restart: always
    command: sh -c "yarn install && yarn start"
    ports:
      - 4040:4040
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      REACT_APP_API_SERVER_URL: http://localhost:6060
      REACT_APP_AUTH0_DOMAIN: dev-tpq6khp7tkgiovnk.us.auth0.com
      REACT_APP_AUTH0_CLIENT_ID: b30pQJpBb7vWeRZOHr346L4y5QnzH3NA
      REACT_APP_AUTH0_CALLBACK_URL: http://localhost:4040/callback